version: "3"

services:
  merlindnode0:
    container_name: merlindnode0
    image: "tendermint/merlindnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-merlind.log}
    volumes:
      - ./build:/merlind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  merlindnode1:
    container_name: merlindnode1
    image: "tendermint/merlindnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-merlind.log}
    volumes:
      - ./build:/merlind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  merlindnode2:
    container_name: merlindnode2
    image: "tendermint/merlindnode"
    environment:
      - ID=2
      - LOG=${LOG:-merlind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/merlind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  merlindnode3:
    container_name: merlindnode3
    image: "tendermint/merlindnode"
    environment:
      - ID=3
      - LOG=${LOG:-merlind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/merlind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
