version: "3"

services:
  fanfurydnode0:
    container_name: fanfurydnode0
    image: "tendermint/fanfurydnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-fanfuryd.log}
    volumes:
      - ./build:/fanfuryd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  fanfurydnode1:
    container_name: fanfurydnode1
    image: "tendermint/fanfurydnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-fanfuryd.log}
    volumes:
      - ./build:/fanfuryd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  fanfurydnode2:
    container_name: fanfurydnode2
    image: "tendermint/fanfurydnode"
    environment:
      - ID=2
      - LOG=${LOG:-fanfuryd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fanfuryd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  fanfurydnode3:
    container_name: fanfurydnode3
    image: "tendermint/fanfurydnode"
    environment:
      - ID=3
      - LOG=${LOG:-fanfuryd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fanfuryd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
