// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fanfury/mint/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the mint module's genesis state.
type GenesisState struct {
	// minter is a space for holding current rewards information.
	Minter Minter `protobuf:"bytes,1,opt,name=minter,proto3" json:"minter"`
	// params defines all the paramaters of the module.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
	// required values for team rewards
	MonthInfo TeamVestingMonthInfo `protobuf:"bytes,3,opt,name=month_info,json=monthInfo,proto3" json:"month_info"`
	// current reduction period start block
	ReductionStartedBlock int64 `protobuf:"varint,4,opt,name=reduction_started_block,json=reductionStartedBlock,proto3" json:"reduction_started_block,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_010051eae705841c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetMinter() Minter {
	if m != nil {
		return m.Minter
	}
	return Minter{}
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMonthInfo() TeamVestingMonthInfo {
	if m != nil {
		return m.MonthInfo
	}
	return TeamVestingMonthInfo{}
}

func (m *GenesisState) GetReductionStartedBlock() int64 {
	if m != nil {
		return m.ReductionStartedBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "fanfury.mint.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("fanfury/mint/v1beta1/genesis.proto", fileDescriptor_010051eae705841c)
}

var fileDescriptor_010051eae705841c = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0xc7, 0xef, 0xda, 0x52, 0x30, 0x3a, 0x1d, 0x15, 0x8f, 0x22, 0x69, 0xe9, 0x54, 0x04, 0x13,
	0xaa, 0xe0, 0xe0, 0xd8, 0x45, 0x3a, 0x14, 0xa5, 0x15, 0x07, 0x97, 0x92, 0xbb, 0xe6, 0xae, 0x41,
	0x93, 0x1c, 0xc9, 0xab, 0xd8, 0x4f, 0xa1, 0x1f, 0xab, 0x63, 0x47, 0x27, 0x91, 0xf6, 0x8b, 0x48,
	0x72, 0x57, 0xa7, 0xe2, 0x16, 0xf2, 0xff, 0xfd, 0xfe, 0xef, 0xf1, 0x50, 0x2f, 0x63, 0x2a, 0x5b,
	0x9a, 0x15, 0x95, 0x42, 0x01, 0x7d, 0x1b, 0x24, 0x1c, 0xd8, 0x80, 0xe6, 0x5c, 0x71, 0x2b, 0x2c,
	0x29, 0x8c, 0x06, 0x1d, 0xb5, 0x2a, 0x86, 0x38, 0x86, 0x54, 0x4c, 0xbb, 0x95, 0xeb, 0x5c, 0x7b,
	0x80, 0xba, 0x57, 0xc9, 0xb6, 0x3b, 0x07, 0xfb, 0xbc, 0xe8, 0x81, 0xde, 0x47, 0x0d, 0x9d, 0xdc,
	0x95, 0xf5, 0x53, 0x60, 0xc0, 0xa3, 0x5b, 0xd4, 0x74, 0x31, 0x37, 0x71, 0xd8, 0x0d, 0xfb, 0xc7,
	0x57, 0xe7, 0xe4, 0xd0, 0x38, 0x32, 0xf6, 0xcc, 0xb0, 0xb1, 0xfe, 0xee, 0x04, 0x93, 0xca, 0x70,
	0x6e, 0xc1, 0x0c, 0x93, 0x36, 0xae, 0xfd, 0xe7, 0x3e, 0x78, 0x66, 0xef, 0x96, 0x46, 0x74, 0x8f,
	0x90, 0xd4, 0x0a, 0x16, 0x33, 0xa1, 0x32, 0x1d, 0xd7, 0xbd, 0x7f, 0x71, 0xd8, 0x7f, 0xe4, 0x4c,
	0x3e, 0x71, 0x0b, 0x42, 0xe5, 0x63, 0xa7, 0x8c, 0x54, 0xa6, 0xab, 0xb6, 0x23, 0xb9, 0xff, 0x88,
	0x6e, 0xd0, 0x99, 0xe1, 0xf3, 0x65, 0x0a, 0x42, 0xab, 0x99, 0x05, 0x66, 0x80, 0xcf, 0x67, 0xc9,
	0xab, 0x4e, 0x5f, 0xe2, 0x46, 0x37, 0xec, 0xd7, 0x27, 0xa7, 0x7f, 0xf1, 0xb4, 0x4c, 0x87, 0x2e,
	0x1c, 0x8e, 0xd6, 0x5b, 0x1c, 0x6e, 0xb6, 0x38, 0xfc, 0xd9, 0xe2, 0xf0, 0x73, 0x87, 0x83, 0xcd,
	0x0e, 0x07, 0x5f, 0x3b, 0x1c, 0x3c, 0xd3, 0x5c, 0xc0, 0x62, 0x99, 0x90, 0x54, 0x4b, 0xea, 0xb6,
	0xb2, 0x85, 0x36, 0x40, 0xab, 0x15, 0x2f, 0xd3, 0x05, 0x13, 0x8a, 0xbe, 0x97, 0x97, 0x86, 0x55,
	0xc1, 0x6d, 0xd2, 0xf4, 0x37, 0xbe, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x07, 0x96, 0x1b,
	0xd6, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReductionStartedBlock != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReductionStartedBlock))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.MonthInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Minter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Minter.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.MonthInfo.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.ReductionStartedBlock != 0 {
		n += 1 + sovGenesis(uint64(m.ReductionStartedBlock))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Minter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonthInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReductionStartedBlock", wireType)
			}
			m.ReductionStartedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReductionStartedBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
